### ISSUE TITLE
accept gtf format

### ISSUE THREAD

**Issue by xiekunwhy** [Kuanhao-Chao/LiftOn#10]
Hi,

It seems that lifton only accept gff3 fort, but gtf also a popular gene structurce annotation format, would you please make some modify to accept gtf as annotation input ?

Best,
Kun

**Comment by Kuanhao-Chao** [comment]
Hi Kun,

I’ve fixed the issue and released a new version of LiftOn (v1.0.5): https://github.com/Kuanhao-Chao/LiftOn/releases/tag/v1.0.5
The error occurred because the IDs for each feature in GTF files are different. 
For instance, it’s `gene_id` for genes, `transcript_id` for transcripts, and so on, whereas in GFF files, it's always `ID`. 
It wasn't properly handled, which caused errors when extracting features from the gffutils database. 

Thanks for reporting this error.
Best,
Kuan-Hao
